### ISSUE TITLE
cannot run in wd node-qt5@0.0.1 node-gyp rebuild

### ISSUE THREAD

**Issue by xlmnxp** [anak10thn/node-qt5#2]
$ sudo npm install
npm WARN lifecycle node-qt5@0.0.1~install: cannot run in wd node-qt5@0.0.1 node-gyp rebuild (wd=/home/xlmnxp/Projects/node-qt5)

**operating system**: Kubuntu lts 18.04 ( KDE lts 5.12)
**operating system type**: 64-bit

**Comment by anak10thn** [comment]
plis use 
```
npm install --unsafe-perm
```
@xlmnxp

**Comment by xlmnxp** [comment]
other problem
```
No package 'Qt5Multimedia' found
Package Qt5Quick was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Quick.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Quick' found
Package Qt5Qml was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Qml.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Qml' found
gyp: Call to 'pkg-config --libs-only-l Qt5Core Qt5Gui Qt5Test Qt5Multimedia Qt5Widgets Qt5Quick Qt5Qml' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-42-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/xlmnxp/Projects/node-qt5
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-qt5@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-qt5@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xlmnxp/.npm/_logs/2018-12-07T17_17_11_156Z-debug.log
```

**Comment by anak10thn** [comment]
install qtdeclarative5-dev qtmultimedia5-dev first, or install all Qt 5 development library (qt*5-dev) package on your ubuntu @xlmnxp

**Comment by xlmnxp** [comment]
it's work fine now :+1: 
thank you

before install you should install `qtdeclarative5-dev` and `qtmultimedia5-dev` first
```bash
apt install qtdeclarative5-dev qtmultimedia5-dev
```

then install module with flag ` --unsafe-perm`
```bash
npm install --unsafe-perm
```
